/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      sans: ["Ubuntu", "ui-sans-serif", "system-ui"],
      // Add a mono family
      mono: ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
    },
    extend: {},
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        light: {
          "primary": "259 94 71",
          "primary-content": "0 0 100",
          "secondary": "314 79 82",
          "secondary-content": "0 0 100",
          "accent": "174 60 63",
          "accent-content": "0 0 100",
          "neutral": "215 28 17",
          "neutral-content": "0 0 80",
          "base-100": "0 0 100",
          "base-200": "0 0 95",
          "base-300": "0 0 90",
          "base-content": "215 28 10",
          "info": "198 93 60",
          "info-content": "0 0 100",
          "success": "158 64 52",
          "success-content": "0 0 100",
          "warning": "43 96 56",
          "warning-content": "215 28 10",
          "error": "0 91 71",
          "error-content": "0 0 100",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "color-scheme": "light", // Required for daisyUI themes object
        },
      },
      {
        dark: {
          "primary": "259 94 71",
          "primary-content": "0 0 100",
          "secondary": "314 79 82",
          "secondary-content": "0 0 100",
          "accent": "174 60 63",
          "accent-content": "0 0 100",
          "neutral": "215 15 30",
          "neutral-content": "0 0 80",
          "base-100": "215 28 17",
          "base-200": "215 28 14",
          "base-300": "215 28 10",
          "base-content": "0 0 80",
          "info": "198 93 60",
          "info-content": "0 0 100",
          "success": "158 64 52",
          "success-content": "0 0 100",
          "warning": "43 96 56",
          "warning-content": "215 28 10",
          "error": "0 91 71",
          "error-content": "0 0 100",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.5rem",
          "--rounded-badge": "1.9rem",
          "--animation-btn": "0.25s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.95",
          "--border-btn": "1px",
          "--tab-border": "1px",
          "--tab-radius": "0.5rem",
          "color-scheme": "dark", // Required for daisyUI themes object
        },
      },
      // You can add other themes here if needed, e.g., "cupcake"
    ],
    // other daisyui options like logs: false can remain if they were there
  },
};