/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedTextRouteImport } from './routes/saved-text'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as CustomTextRouteImport } from './routes/custom-text'
import { Route as IndexRouteImport } from './routes/index'

const SavedTextRoute = SavedTextRouteImport.update({
  id: '/saved-text',
  path: '/saved-text',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTextRoute = CustomTextRouteImport.update({
  id: '/custom-text',
  path: '/custom-text',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-text': typeof CustomTextRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-text': typeof CustomTextRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-text': typeof CustomTextRoute
  '/practice': typeof PracticeRoute
  '/saved-text': typeof SavedTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/custom-text' | '/practice' | '/saved-text'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/custom-text' | '/practice' | '/saved-text'
  id: '__root__' | '/' | '/custom-text' | '/practice' | '/saved-text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomTextRoute: typeof CustomTextRoute
  PracticeRoute: typeof PracticeRoute
  SavedTextRoute: typeof SavedTextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved-text': {
      id: '/saved-text'
      path: '/saved-text'
      fullPath: '/saved-text'
      preLoaderRoute: typeof SavedTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-text': {
      id: '/custom-text'
      path: '/custom-text'
      fullPath: '/custom-text'
      preLoaderRoute: typeof CustomTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomTextRoute: CustomTextRoute,
  PracticeRoute: PracticeRoute,
  SavedTextRoute: SavedTextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
